#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""Version 3 database schema support for Whatsapp Msgstore Viewer.
This package is automatically discovered by the application; it only needs
 to expose the `Database` class implemented in `db.py`.
"""

__author__ = "Auto-generated by AI"
__version__ = "1.0.0"

if __name__ == '__main__':
    pass 